SOURCES = ex1.c ex2.c ex3.c
all:  ${SOURCES}
	gcc ex1.c -lm -o ex1.out -lm -std=c99
	gcc ex2.c -lm -o ex2.out -lm -std=c99
	gcc ex3.c -lm -o ex3.out -lm -std=c99

ex1:    ex1.c
	./ex1.out

ex2:    ex2.c
	./ex2.out

ex3:    ex3.c
	./ex3.out

clean:
	rm ex1.out ex2.out ex3.out

